************************************
*     Merge CIF and Matching	   *
************************************
* Last update: 2015-01-13 (JN) Add $ROOTDIR
* Adding INE codes to CIF data
* CifAgrupadasINE.dta contains data about ICO targets by muncipio (ID: INE code)

clear all
set more off

use $ROOTDIR\CIF\CifAgrupadas.dta
//Renaming some muncipios names in order to fit the match
replace NOMBRE_ENTIDAD = "VILAJUIGA" if NOMBRE_ENTIDAD == "VILAJUÏGA"
replace NOMBRE_ENTIDAD = "GIJON" if NOMBRE_ENTIDAD == "GIJON/XIXON"
replace NOMBRE_ENTIDAD = "GUADASSÉQUIES" if NOMBRE_ENTIDAD == "GUADASSEQUIES"
replace NOMBRE_ENTIDAD = "SAUS" if NOMBRE_ENTIDAD == "SAUS, CAMALLERA I LLAMPAIES"
replace NOMBRE_ENTIDAD = "MONTUIRI" if NOMBRE_ENTIDAD == "MONTUÏRI"
replace NOMBRE_ENTIDAD = "ALDEA DE SAN NICOLÁS" if NOMBRE_ENTIDAD == "ALDEA DE SAN NICOLAS"
replace NOMBRE_ENTIDAD = "MASSALAVÉS" if NOMBRE_ENTIDAD == "MASSALAVES"
replace NOMBRE_ENTIDAD = "HORCAJO DE LA SIERRA" if NOMBRE_ENTIDAD == "HORCAJO DE LA SIERRA-AOSLOS"
replace NOMBRE_ENTIDAD = "HONDON DE LAS NIEVES/FONDO DE LES NEUS" if NOMBRE_ENTIDAD == "FONDO DE LES NEUS"
replace NOMBRE_ENTIDAD = "VILAFRANCA DE BONANY" if NOMBRE_ENTIDAD == "VILAFRANC DE BONANY"
replace NOMBRE_ENTIDAD = "VIMBODÍ I POBLET" if NOMBRE_ENTIDAD == "VIMBODI I POBLET"
replace NOMBRE_ENTIDAD = "VILLARREAL/VILA-REAL" if NOMBRE_ENTIDAD == "VILA-REAL"
replace NOMBRE_ENTIDAD = "PALMA DE MALLORCA" if NOMBRE_ENTIDAD == "PALMA"
replace NOMBRE_ENTIDAD = "VALL DE EBO" if NOMBRE_ENTIDAD == "VALL D'EBO"
replace NOMBRE_ENTIDAD = "CALPE/CALP" if NOMBRE_ENTIDAD == "CALP"
replace NOMBRE_ENTIDAD = "VILLAFRANCA DEL CID / VILAFRANCA" if NOMBRE_ENTIDAD == "VILLAFRANCA DEL CID/VILAFRANCA"
replace NOMBRE_ENTIDAD = "PINOSO/PINOS" if NOMBRE_ENTIDAD == "PINOSO/PINOS"
replace NOMBRE_ENTIDAD = "TORRE D'EN DOMÉNEC" if NOMBRE_ENTIDAD == "TORRE D'EN DOMENEC"
replace NOMBRE_ENTIDAD = "MONTICHELVO" if NOMBRE_ENTIDAD == "MONTITXELVO/MONTICHELVO"
replace NOMBRE_ENTIDAD = "ARES DEL MAESTRE" if NOMBRE_ENTIDAD == "ARES DEL MAESTRAT"
replace NOMBRE_ENTIDAD = "MAHON" if NOMBRE_ENTIDAD == "MAO"
replace NOMBRE_ENTIDAD = "BURRIANA" if NOMBRE_ENTIDAD == "BORRIANA/BURRIANA"
replace NOMBRE_ENTIDAD = "SAN ILDEFONSO" if NOMBRE_ENTIDAD == "REAL SITIO DE SAN ILDEFONSO"
replace NOMBRE_ENTIDAD = "JALON/XALO" if NOMBRE_ENTIDAD == "XALO"
replace NOMBRE_ENTIDAD = "PASSANANT" if NOMBRE_ENTIDAD == "PASSANANT I BELLTALL"
replace NOMBRE_ENTIDAD = "NÁJERA" if NOMBRE_ENTIDAD == "NAJERA"
replace NOMBRE_ENTIDAD = "SERRADA, LA" if NOMBRE_ENTIDAD == "SERRADA"
replace NOMBRE_ENTIDAD = "PASSANANT I BELLTALL" if NOMBRE_ENTIDAD == "PASSANANT"

//Merging with Matching.dta (INE codes)
merge 1:1 NOMBRE_ENTIDAD CCAA using $ROOTDIR\Matching\Matching.dta 


//We do not want supramuncipal data
split NOMBRE_ENTIDAD, parse(" ")
drop if NOMBRE_ENTIDAD1 == "DIPUTACION"
drop if NOMBRE_ENTIDAD1 == "CABILDO"
drop if NOMBRE_ENTIDAD1 == "CONSEJO"
drop  NOMBRE_ENTIDAD1 NOMBRE_ENTIDAD2 NOMBRE_ENTIDAD3 NOMBRE_ENTIDAD4 NOMBRE_ENTIDAD5 NOMBRE_ENTIDAD1 NOMBRE_ENTIDAD6 NOMBRE_ENTIDAD7
drop _merge

save $ROOTDIR\TablasUnidas\CifAgrupadasINE.dta, replace
